function Hdyn_exp_qM = f_Hdyn(in1,M)
%F_HDYN
%    HDYN_EXP_QM = F_HDYN(IN1,M)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2021 18:41:28

d3 = in1(3,:);
t2 = in1(2,:);
t3 = cos(t2);
t4 = sin(t2);
t5 = d3.^2;
t6 = M.*d3.*2.0;
t8 = pi.*4.3875e-2;
t9 = d3.*pi.*8.775e-2;
t11 = pi.*4.3875e-3;
t7 = t4.^2;
t10 = M+t8;
t12 = -t11;
t13 = (t4.*t10)./1.0e+1;
t15 = t6+t9+t12;
t14 = -t13;
t16 = (t3.*t15)./2.0e+1;
t17 = -t16;
Hdyn_exp_qM = reshape([M./1.0e+2+pi.*5.85e-4+t7.*pi.*1.4625e-4-d3.*t7.*pi.*4.3875e-3+M.*t5.*t7+t5.*t7.*t8,t17,t14,t17,pi.*1.4625e-4-d3.*pi.*4.3875e-3+M.*t5+t5.*t8,0.0,t14,0.0,t10],[3,3]);
