function out1 = f_JA(in1)
%F_JA
%    OUT1 = F_JA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2021 18:41:21

t1 = in1(1,:);
out1 = reshape([0.0,0.0,1.0,cos(t1),sin(t1),0.0,0.0,0.0,0.0],[3,3]);
