function out1 = f_YG(in1)
%F_YG
%    OUT1 = F_YG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2021 18:41:44

d3 = in1(3,:);
t2 = in1(2,:);
out1 = [0.0;d3.*sin(t2).*(-9.81e+2./1.0e+2);cos(t2).*(9.81e+2./1.0e+2)];
