function out1 = f_YH(in1)
%F_YH
%    OUT1 = F_YH(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2021 18:41:28

d3 = in1(3,:);
t2 = in1(2,:);
t3 = cos(t2);
t4 = sin(t2);
t5 = d3.^2;
t6 = t4./1.0e+1;
t8 = (d3.*t3)./1.0e+1;
t7 = -t6;
t9 = -t8;
out1 = reshape([t4.^2.*t5+1.0./1.0e+2,t9,t7,t9,t5,0.0,t7,0.0,1.0],[3,3]);
